// Weather system configurations
export const WEATHER_TYPES = ['sunny', 'rainy', 'foggy', 'windy']

export const WEATHER_EFFECTS = {
  sunny: {
    name: 'Sonnig',
    icon: '☀️',
    description: 'Keine besonderen Effekte',
    playerSpeedMod: 1,
    enemySpeedMod: 1,
    rangeMod: 1,
    fogNear: 40,
    fogFar: 100,
    fogColor: 0x87CEEB,
    sunIntensity: 1.5,
  },
  rainy: {
    name: 'Regen',
    icon: '🌧️',
    description: '-20% Feind-Speed',
    playerSpeedMod: 1,
    enemySpeedMod: 0.8,
    rangeMod: 1,
    fogNear: 30,
    fogFar: 70,
    fogColor: 0x6688AA,
    sunIntensity: 0.8,
    showRain: true,
  },
  foggy: {
    name: 'Nebel',
    icon: '🌫️',
    description: '-30% Reichweite',
    playerSpeedMod: 1,
    enemySpeedMod: 1,
    rangeMod: 0.7,
    fogNear: 15,
    fogFar: 40,
    fogColor: 0xCCCCCC,
    sunIntensity: 1,
    showFog: true,
  },
  windy: {
    name: 'Wind',
    icon: '💨',
    description: '+20% Speed',
    playerSpeedMod: 1.2,
    enemySpeedMod: 1,
    rangeMod: 1,
    fogNear: 40,
    fogFar: 100,
    fogColor: 0x87CEEB,
    sunIntensity: 1.5,
  },
}
